Add CCP definition
seecloud/security pull request #13
Opened 2016-12-23 14:34 UTC by corest

- Dockerfile template
- security-api service definition

2016-12-23 14:51 UTC, redixin commented on service/files/security.conf.j2
> +flask:
This sections is not needed

2016-12-26 08:44 UTC, akscram requested changes

2016-12-26 08:44 UTC, akscram commented on security/config.py
> +    "flask": {
This section is not needed because it is not used in the service.

2016-12-28 12:19 UTC, akscram requested changes
Looks good to me, bu we need to merge it only after #15 .

2017-01-05 23:25 UTC, akscram approved these changes

2017-01-06 08:45 UTC, redixin approved these changes

2017-01-06 08:45 UTC, merged